version: "3"

services:
  dummy-api:
    build: ./barokey-dummy
    ports:
      - "8080:8080"
    volumes:
      - ./barokey-dummy:/workspace

  api:
    build: ./barokey-server
    ports:
      - "3000:3000"

  frontend-build:
    image: node:lts-alpine
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install -D
        npm run build
    restart: "no"
    volumes:
      - ./barokey-client/:/app
      - client-dist:/app/build
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend-build
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Seoul"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - client-dist:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  client-dist:
